import {NextResponse} from 'next/server'
import {getServerSession} from 'next-auth'
import Groq from 'groq-sdk'
import {z} from 'zod'
import {authOptions} from '@/lib/auth'
import {prisma} from '@/lib/db'

const RequestSchema=z.object({
  prompt:z.string().min(3).max(4000)
})

const BookSchema=z.object({
  title:z.string().min(1).max(200),
  author:z.string().min(1).max(150),
  description:z.string().max(5000).default(''),
  category:z.string().min(1).max(100),
  language:z.string().max(60).default('English'),
  cover_url:z.string().max(2000).default(''),
  pdf_url:z.string().max(2000).default(''),
  page_count:z.number().int().min(0).max(50000).default(0),
  file_size:z.string().max(50).default('Unknown'),
  tags:z.string().max(1000).default(''),
  source_url:z.string().max(2000).default(''),
  license_note:z.string().max(500).default(''),
  license_ok:z.boolean().default(false)
})

type Candidate= z.infer<typeof BookSchema>

function extractJson(text:string){
  const match=text.match(/\{[\s\S]*\}/)
  if(!match) throw new Error('Groq did not return valid JSON')
  return JSON.parse(match[0])
}

export async function POST(req:Request){
  const session=await getServerSession(authOptions)

  if(!session){
    return NextResponse.json(
      {error:'Unauthorized'},
      {status:401}
    )
  }

  if(!process.env.GROQ_API_KEY){
    return NextResponse.json(
      {error:'GROQ_API_KEY is not configured'},
      {status:500}
    )
  }

  try{
    const body=RequestSchema.parse(await req.json())

    const groq=new Groq({
      apiKey:process.env.GROQ_API_KEY
    })

    /*
     * First pass:
     * Groq searches the web for candidate books.
     */
    const search=await groq.chat.completions.create({
      model:'openai/gpt-oss-120b',
      messages:[
        {
          role:'system',
          content:`
You are the G.I Bookshelf AI Librarian.

Find books matching the administrator's request.

IMPORTANT:
- Prefer public-domain, openly licensed, or clearly authorized free books.
- Do not recommend pirated copies.
- Look for legitimate publisher, author, university, archive,
  or recognized open-book sources.
- Find a real source/download URL when available.
- Do not invent URLs.
- Return useful source details and URLs.
          `.trim()
        },
        {
          role:'user',
          content:body.prompt
        }
      ],
      tools:[
        {type:'browser_search'}
      ],
      tool_choice:'required'
    })

    const searchMessage=search.choices[0]?.message

    const searchText=[
      searchMessage?.content||'',
      JSON.stringify(
        (searchMessage as unknown as {
          executed_tools?:unknown
        })?.executed_tools||''
      )
    ].join('\n')

    /*
     * Second pass:
     * Convert search findings into predictable book objects.
     */
    const structured=await groq.chat.completions.create({
      model:'openai/gpt-oss-120b',
      messages:[
        {
          role:'system',
          content:`
Extract book records from the supplied research.

For the "description" field:
- Write a short, clear description of the book.
- Use simple language that a normal reader can understand.
- Explain what the book is about and what the reader can learn or experience.
- Keep it to 1-2 sentences.
- Maximum 300 characters.
- Do not repeat the book title.
- Do not mention that the description was generated by AI.
- Do not exaggerate or invent facts.
- Base the description only on reliable information in the research.

Return ONLY JSON in this exact shape:

{
  "books": [
    {
      "title": "...",
      "author": "...",
      "description": "...",
      "category": "...",
      "language": "English",
      "cover_url": "",
      "pdf_url": "",
      "page_count": 0,
      "file_size": "Unknown",
      "tags": "tag1, tag2",
      "source_url": "...",
      "license_note": "...",
      "license_ok": true
    }
  ]
}

Rules:
- Never invent URLs.
- pdf_url must be an actual PDF/download URL found in the research.
- license_ok=true only when the research provides a credible indication
  that the book is public domain, openly licensed, or authorized for free
  redistribution.
- If licensing is unclear, set license_ok=false.
- Do not include pirated sources.
          `.trim()
        },
        {
          role:'user',
          content:searchText
        }
      ]
    })

    const raw=structured.choices[0]?.message?.content||'{}'
    const parsed=extractJson(raw)

    const booksRaw=Array.isArray(parsed.books)?parsed.books:[]

    const candidates:Candidate[]=[]

    for(const item of booksRaw){
      try{
        const book=BookSchema.parse(item)

        if(!book.title || !book.pdf_url) continue

        candidates.push(book)
      }catch{}
    }

    const imported=[]
    const skipped=[]

    for(const book of candidates){
      if(!book.license_ok){
        skipped.push({
          title:book.title,
          reason:'License/source could not be verified'
        })
        continue
      }

      const duplicate=await prisma.book.findFirst({
        where:{
          title:book.title,
          author:book.author
        }
      })

      if(duplicate){
        skipped.push({
          title:book.title,
          reason:'Already exists'
        })
        continue
      }

      const created=await prisma.book.create({
        data:{
          title:book.title,
          author:book.author,
          description:book.description,
          category:book.category,
          language:book.language,
          cover_url:book.cover_url||
            'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&h=800&fit=crop',
          pdf_url:book.pdf_url,
          page_count:book.page_count,
          file_size:book.file_size,
          tags:book.tags,
          published:false
        }
      })

      imported.push({
        id:created.id,
        title:created.title,
        author:created.author,
        category:created.category
      })
    }

    return NextResponse.json({
      ok:true,
      requested:body.prompt,
      found:candidates.length,
      imported,
      skipped
    })

  }catch(error){
    console.error('AI Librarian error:',error)

    return NextResponse.json({
      error:error instanceof Error
        ?error.message
        :'AI Librarian failed'
    },{
      status:500
    })
  }
}
